i think this is working re-alignment. still need to fix the header though

diff --git a/bin/speedseq b/bin/speedseq
--- a/bin/speedseq
+++ b/bin/speedseq
@@ -31,11 +31,11 @@ function source_binaries() {
 	TABIX=`which tabix || true`
 	LUMPY=`which lumpy || true`
 	PAIREND_DISTRO=`which pairend_distro.py || true`
-	BEDPETOVCF="$SPEEDSEQ_HOME/src/sv-tools/bedpeToVcf"
-	SVTYPER="$SPEEDSEQ_HOME/src/svtyper/svtyper"
+	BEDPETOVCF=$SPEEDSEQ_HOME/bin/bedpeToVcf
+	SVTYPER=$SPEEDSEQ_HOME/bin/svtyper
 	PYTHON27=`which python2.7 || true`
-	SAMTOOLS=`which samtools || true`
-	BAMUTIL=`which bam || true`
+	MBUFFER=$SPEEDSEQ_HOME/bin/mbuffer
+	BAMTOFASTQ=$SPEEDSEQ_HOME/bin/bamtofastq.py
     fi
 }
 
@@ -48,10 +48,11 @@ Author: Colby Chiang (cc2qe@virginia.edu)
 
 usage:   speedseq <command> [options]
 
-command: aln      align fastq files with BWA-MEM
+command: align    align fastq files with BWA-MEM
          var      call variants with freebayes
          somatic  call somatic variants in a tumor/normal pair with freebayes
          sv       call SVs with lumpy
+         re-align re-align from a coordinate sorted BAM file
 
 options: -h       show this message
 "
@@ -87,10 +88,10 @@ function somatic_filter() {
 }
 
 # alignment with BWA-MEM
-function aln() {
-    function aln_usage() {
+function align() {
+    function align_usage() {
 	echo "
-usage:   speedseq aln [options] <reference.fa> <in1.fq> [in2.fq]
+usage:   speedseq align [options] <reference.fa> <in1.fq> [in2.fq]
 
 positional args:
          reference.fa
@@ -110,8 +111,6 @@ alignment options:
                   specify the mean, standard deviation (10% of the mean if absent), max
                     (4 sigma from the mean if absent) and min of the insert size distribution.
                     FR orientation only. [inferred]
-         -b       re-align from a coordinate sorted BAM file (does not require fastq files)
-         -g STR   re-align this read group from the coordinate sorted BAM file
 
 samblaster options:
          -i       include duplicates in splitters and discordants
@@ -131,7 +130,7 @@ global options:
     # Check options passed in.
     if test -z "$2"
     then
-	aln_usage
+	align_usage
 	exit 1
     fi
 
@@ -148,15 +147,13 @@ global options:
     TEMP_DIR="./temp"
     VERBOSE=0
     INS_DIST=""
-    REALIGN_BAM=0
-    REALIGN_RG=""
     SORT_MEM=20 # amount of memory for sorting, in gigabytes
 
-    while getopts ":hw:o:R:pic:m:M:t:T:g:I:vbK:" OPTION
+    while getopts ":hw:o:R:pic:m:M:t:T:I:vK:" OPTION
     do
 	case "${OPTION}" in
 	    h)
-		aln_usage
+		align_usage
 		exit 1
 		;;
 	    R)
@@ -187,12 +184,6 @@ global options:
 	    T)
 		TEMP_DIR="$OPTARG"
 		;;
-	    b)
-		REALIGN_BAM=1
-		;;
-	    g)
-		REALIGN_RG="$OPTARG"
-		;;
 	    I)
 		INS_DIST="-I $OPTARG"
 		;;
@@ -205,36 +196,7 @@ global options:
 	esac
     done
 
-    if [[ $REALIGN_BAM -eq 1 ]]
-    then
-	REF="${@:${OPTIND}:1}"
-	IN_BAM="${@:$((${OPTIND}+1)):1}"
-	if [[ -z "$OUTPUT" ]]
-	then
-	    OUTPUT=`basename "$IN_BAM" ".bam"`
-	fi
-
-        # Check that the ref and bam files exist
-	if [[ -z "$REF" ]] || [[ ! -f "$REF" ]]
-	then
-            aln_usage
-            echo -e "Error: Reference file $REF not found.\n"
-            exit 1
-	elif [[ -z "$IN_BAM" ]] || [[ ! -e "$IN_BAM" ]]
-	then
-            aln_usage
-            echo -e "Error: BAM file $IN_BAM not found.\n"
-            exit 1
-	fi
-	mkdir -p $TEMP_DIR
-	if [[ ! -e $TEMP_DIR/fq_pipe ]]
-	then
-	    mkfifo $TEMP_DIR/fq_pipe
-	fi
-	FQ="$TEMP_DIR/fq_pipe"
-	$SAMTOOLS view -h -F 0x0100 -r <(echo "$REALIGN_RG" | tr ',' '\n') $IN_BAM | $BAMUTIL bam2Fastq --in - --merge  --unpairedOut /dev/null > $TEMP_DIR/fq_pipe &
-
-    elif [[ "$INTERLEAVED" -eq 1 ]]
+    if [[ "$INTERLEAVED" -eq 1 ]]
     then
 	REF="${@:${OPTIND}:1}"
 	FQ="${@:$((${OPTIND}+1)):1}"
@@ -246,12 +208,12 @@ global options:
         # Check that the ref and fastq files exist
 	if [[ -z "$REF" ]] || [[ ! -f "$REF" ]]
 	then
-            aln_usage
+            align_usage
             echo -e "Error: Reference file $REF not found.\n"
             exit 1
 	elif [[ -z "$FQ" ]] || [[ ! -e "$FQ" ]]
 	then
-            aln_usage
+            align_usage
             echo -e "Error: Fastq file $FQ not found.\n"
             exit 1
 	fi
@@ -267,17 +229,17 @@ global options:
         # Check that the ref and fastq files exist
 	if [[ -z "$REF" ]] || [[ ! -f "$REF" ]]
 	then
-            aln_usage
+            align_usage
             echo -e "Error: Reference file $REF not found.\n"
             exit 1
 	elif [[ -z "$FQ1" ]] || [[ ! -e "$FQ1" ]]
 	then
-            aln_usage
+            align_usage
             echo -e "Error: Fastq file $FQ1 not found.\n"
             exit 1
 	elif [[ -z "$FQ2" ]] || [[ ! -e "$FQ2" ]]
 	then
-            aln_usage
+            align_usage
             echo -e "Error: Fastq file $FQ2 not found. (single-end reads not supported)\n"
             exit 1
 	fi
@@ -288,7 +250,7 @@ global options:
     # Check for readgroup flag
     if [[ -z $RG_FMT ]]
     then
-	aln_usage
+	align_usage
 	echo -e "Error: no readgroup found. Please set a readgroup with the -R flag.\n"
 	exit 1
     fi
@@ -298,17 +260,17 @@ global options:
 
     if [[ -z "$BWA" ]]
     then
-	aln_usage
+	align_usage
         echo -e "Error: bwa executable not found. Please set path in $SPEEDSEQ_DIR/speedseq.config file\n"
         exit 1
     elif [[ -z  "$SAMBLASTER" ]]
     then
-	aln_usage
+	align_usage
         echo -e "Error: samblaster executable not found. Please set path in $SPEEDSEQ_DIR/speedseq.config file\n"
         exit 1
     elif [[ -z "$SAMBAMBA" ]]
     then
-	aln_usage
+	align_usage
         echo -e "Error: sambamba executable not found. Please set path in $SPEEDSEQ_DIR/speedseq.config file\n"
         exit 1
     fi
@@ -1655,6 +1617,262 @@ cat  $TEMP_DIR/$OUTBASE.sv.vcf \\
     exit 0
 }
 
+function re-align() {
+    function re-align_usage() {
+	echo "
+usage:   speedseq re-align [options] <reference.fa> <in.bam>
+
+positional args:
+         reference.fa
+                  fasta file (indexed with bwa)
+         in.bam   re-align from a coordinate sorted BAM file
+
+alignment options:
+         -o STR   output prefix [in.realign]
+         -I FLOAT[,FLOAT[,INT[,INT]]]
+                  specify the mean, standard deviation (10% of the mean if absent), max
+                    (4 sigma from the mean if absent) and min of the insert size distribution.
+                    FR orientation only. [inferred]
+         -g STR   re-align this read group from the coordinate sorted BAM file
+         -n       rename reads for smaller file size (ONLY WORKS FOR re-alignment right now)
+         -t INT   threads [1]
+         -T DIR   temp directory [./temp]
+
+samblaster options:
+         -i       include duplicates in splitters and discordants
+         -c INT   maximum number of split alignments for a read to be included in splitter file [2]
+         -m INT   minimum non-overlapping base pairs between two alignments for a read to be included in splitter file [20]
+
+sambamba options:
+         -M       amount of memory in GB to be used for sorting [20]
+
+global options:
+         -K FILE  path to speedseq.config file (default: same directory as speedseq)
+         -v       verbose
+         -h       show this message
+"
+    }
+
+    # Check options passed in.
+    if test -z "$2"
+    then
+	re-align_usage
+	exit 1
+    fi
+
+    # set defaults
+    SPEEDSEQ_DIR=`dirname $0`
+    CONFIG="$SPEEDSEQ_DIR/speedseq.config"
+    INTERLEAVED=0
+    RG_FMT=""
+    OUTPUT=""
+    INCLUDE_DUPS="--excludeDups"
+    MAX_SPLIT_COUNT=2
+    MIN_NON_OVERLAP=20
+    THREADS=1
+    TEMP_DIR="./temp"
+    VERBOSE=0
+    INS_DIST=""
+    REALIGN_RG=""
+    RENAME=""
+    SORT_MEM=20 # amount of memory for sorting, in gigabytes
+
+    while getopts ":hw:o:R:pic:m:M:t:T:g:I:nvK:" OPTION
+    do
+	case "${OPTION}" in
+	    h)
+		re-align_usage
+		exit 1
+		;;
+	    R)
+		RG="$OPTARG"
+		RG_FMT="-R '$OPTARG'"
+		;;
+	    p)
+		INTERLEAVED=1
+		;;
+	    o)
+		OUTPUT="$OPTARG"
+		;;
+	    i)
+		INCLUDE_DUPS=""
+		;;
+	    c)
+		MAX_SPLIT_COUNT="$OPTARG"
+		;;
+	    m)
+		MIN_NON_OVERLAP="$OPTARG"
+		;;
+	    M)
+		SORT_MEM="$OPTARG"
+		;;
+	    n)
+		RENAME="-n"
+		;;
+	    t)
+		THREADS="$OPTARG"
+		;;
+	    T)
+		TEMP_DIR="$OPTARG"
+		;;
+	    g)
+		REALIGN_RG="-r $OPTARG"
+		;;
+	    I)
+		INS_DIST="-I $OPTARG"
+		;;
+	    v)
+		VERBOSE=1
+		;;
+	    K)
+		CONFIG="$OPTARG"
+		;;
+	esac
+    done
+
+    REF="${@:${OPTIND}:1}"
+    IN_BAM="${@:$((${OPTIND}+1)):1}"
+    if [[ -z "$OUTPUT" ]]
+    then
+	OUTPUT=`basename "$IN_BAM" ".bam"`".realign"
+    fi
+
+    # Check that the ref and bam files exist
+    if [[ -z "$REF" ]] || [[ ! -f "$REF" ]]
+    then
+	re-align_usage
+	echo -e "Error: Reference file $REF not found.\n"
+	exit 1
+    elif [[ -z "$IN_BAM" ]] || [[ ! -e "$IN_BAM" ]]
+    then
+	re-align_usage
+	echo -e "Error: BAM file $IN_BAM not found.\n"
+	exit 1
+    fi
+
+    # Check the for the relevant binaries
+    source_binaries $CONFIG
+    if [[ -z "$BWA" ]]
+    then
+	re-align_usage
+        echo -e "Error: bwa executable not found. Please set path in $SPEEDSEQ_DIR/speedseq.config file\n"
+        exit 1
+    elif [[ -z  "$SAMBLASTER" ]]
+    then
+	re-align_usage
+        echo -e "Error: samblaster executable not found. Please set path in $SPEEDSEQ_DIR/speedseq.config file\n"
+        exit 1
+    elif [[ -z "$SAMBAMBA" ]]
+    then
+	re-align_usage
+        echo -e "Error: sambamba executable not found. Please set path in $SPEEDSEQ_DIR/speedseq.config file\n"
+        exit 1
+    elif [[ -z "$MBUFFER" ]]
+    then
+	re-align_usage
+	echo -e "Error: mbuffer executable not found. Please set path in $SPEEDSEQ_DIR/speedseq.config file\n"
+	exit 1
+    elif [[ -z "$BAMTOFASTQ" ]]
+    then
+	re-align_usage
+	echo -e "Error: bamtofastq.py executable not found. Please set path in $SPEEDSEQ_DIR/speedseq.config file\n"
+	exit 1
+    fi
+
+    # # Check for readgroup flag
+    # if [[ -z $RG_FMT ]]
+    # then
+    # 	align_usage
+    # 	echo -e "Error: no readgroup found. Please set a readgroup with the -R flag.\n"
+    # 	exit 1
+    # fi
+
+    # set the output name
+    OUTBASE=`basename "$OUTPUT"`
+
+    # create the virtual file for fastq pipe
+    mkdir -p $TEMP_DIR
+    if [[ ! -e $TEMP_DIR/fq_pipe ]]
+    then
+	mkfifo $TEMP_DIR/fq_pipe
+    fi
+    FQ="$TEMP_DIR/fq_pipe"
+    if [[ $VERBOSE -eq 1 ]]
+    then
+	echo "$PYTHON27 $BAMTOFASTQ $REALIGN_RG $RENAME -i $IN_BAM | $MBUFFER -m 1G > $TEMP_DIR/fq_pipe &"
+    fi
+    $PYTHON27 $BAMTOFASTQ $REALIGN_RG $RENAME -i $IN_BAM | $MBUFFER -m 1G > $TEMP_DIR/fq_pipe &
+
+    echo "Aligning..."
+    if [[ $VERBOSE -eq 1 ]]
+    then
+	echo "
+        mkdir -p $TEMP_DIR/full $TEMP_DIR/spl $TEMP_DIR/disc
+        mkfifo $TEMP_DIR/spl_pipe $TEMP_DIR/disc_pipe"
+    fi
+
+    # create temp files
+    mkdir -p $TEMP_DIR/full $TEMP_DIR/spl $TEMP_DIR/disc
+    if [[ ! -e $TEMP_DIR/spl_pipe ]]
+    then
+	mkfifo $TEMP_DIR/spl_pipe
+    fi
+    if [[ ! -e $TEMP_DIR/disc_pipe ]]
+    then
+	mkfifo $TEMP_DIR/disc_pipe
+    fi
+
+    # alignment command
+    if [[ $VERBOSE -eq 1 ]]
+    then
+	echo -e "
+    $BWA mem -t $THREADS -C -M -p $INS_DIST $RG_FMT $REF $FQ | \\
+	$SAMBLASTER $INCLUDE_DUPS --addMateTags --maxSplitCount $MAX_SPLIT_COUNT --minNonOverlap $MIN_NON_OVERLAP --splitterFile $TEMP_DIR/spl_pipe --discordantFile $TEMP_DIR/disc_pipe | \\
+	$SAMBAMBA view -S -f bam -l 0 /dev/stdin | \\
+	$SAMBAMBA sort -t $THREADS -m $((${SORT_MEM}-2))G --tmpdir=$TEMP_DIR/full -o $OUTPUT.bam /dev/stdin
+
+    $SAMBAMBA view -S -f bam -l 0 $TEMP_DIR/spl_pipe | \\
+	$SAMBAMBA sort -t 4 -m 1G --tmpdir=$TEMP_DIR/spl -o $OUTPUT.splitters.bam /dev/stdin
+    $SAMBAMBA view -S -f bam $TEMP_DIR/disc_pipe | \\
+	$SAMBAMBA sort -t 4 -m 1G --tmpdir=$TEMP_DIR/disc -o $OUTPUT.discordants.bam /dev/stdin"
+    fi
+
+    echo "
+    $BWA mem -t $THREADS -C -M -p $INS_DIST $RG_FMT $REF $FQ | \
+	$SAMBLASTER $INCLUDE_DUPS --addMateTags --maxSplitCount $MAX_SPLIT_COUNT --minNonOverlap $MIN_NON_OVERLAP --splitterFile $TEMP_DIR/spl_pipe --discordantFile $TEMP_DIR/disc_pipe | \
+	$SAMBAMBA view -S -f bam -l 0 /dev/stdin | \
+	$SAMBAMBA sort -t $THREADS -m $((${SORT_MEM}-2))G --tmpdir=$TEMP_DIR/full -o $OUTPUT.bam /dev/stdin
+
+    $SAMBAMBA view -S -f bam -l 0 $TEMP_DIR/spl_pipe | \
+	$SAMBAMBA sort -t 4 -m 1G --tmpdir=$TEMP_DIR/spl -o $OUTPUT.splitters.bam /dev/stdin
+    $SAMBAMBA view -S -f bam $TEMP_DIR/disc_pipe | \
+	$SAMBAMBA sort -t 4 -m 1G --tmpdir=$TEMP_DIR/disc -o $OUTPUT.discordants.bam /dev/stdin
+    " | parallel -j 3
+    
+    # index the files
+    if [[ $VERBOSE -eq 1 ]]
+    then
+	echo -e "
+        $SAMBAMBA index $OUTPUT.bam
+            $SAMBAMBA index $OUTPUT.discordants.bam
+            $SAMBAMBA index $OUTPUT.splitters.bam"
+    fi
+
+    echo "
+    $SAMBAMBA index $OUTPUT.bam
+    $SAMBAMBA index $OUTPUT.discordants.bam
+    $SAMBAMBA index $OUTPUT.splitters.bam
+    " | parallel -j 3
+
+    # clean up
+    rm -r $TEMP_DIR
+
+    echo "Done"
+
+    # exit cleanly
+    exit 0
+}
+
 # Show usage when there are no arguments.
 if test -z "$1"
 then
@@ -1680,8 +1898,8 @@ done
 
 # call the function
 case "$1" in 
-    'aln')
-	aln "${@:2}"
+    'align')
+	align "${@:2}"
 	;;
     'var')
 	var "${@:2}"
@@ -1692,8 +1910,8 @@ case "$1" in
     'sv')
 	sv "${@:2}"
 	;;
-    're-aln')
-	re-aln "${@:2}"
+    're-align')
+	re-align "${@:2}"
 	;;
     *)
 	usage
