basic realignment

diff --git a/bin/speedseq b/bin/speedseq
--- a/bin/speedseq
+++ b/bin/speedseq
@@ -102,9 +102,10 @@ alignment options:
          -o STR   output prefix [in1.fq]
          -R       read group header line such as \"@RG\tID:libraryname\tSM:samplename\" (required)
          -p       first fastq file consists of interleaved paired-end sequences
-         -b       re-align from a coordinate sorted BAM file (does not require fastq files)
          -t INT   threads [1]
          -T DIR   temp directory [./temp]
+         -b       re-align from a coordinate sorted BAM file (does not require fastq files)
+         -g STR   re-align this read group from the coordinate sorted BAM file
 
 samblaster options:
          -i       include duplicates in splitters and discordants
@@ -141,9 +142,10 @@ global options:
     TEMP_DIR="./temp"
     VERBOSE=0
     REALIGN_BAM=0
+    REALIGN_RG=""
     SORT_MEM=20 # amount of memory for sorting, in gigabytes
 
-    while getopts ":hw:o:R:pic:m:M:t:T:vbK:" OPTION
+    while getopts ":hw:o:R:pic:m:M:t:T:g:vbK:" OPTION
     do
 	case "${OPTION}" in
 	    h)
@@ -181,6 +183,9 @@ global options:
 	    b)
 		REALIGN_BAM=1
 		;;
+	    g)
+		REALIGN_RG="$OPTARG"
+		;;
 	    v)
 		VERBOSE=1
 		;;
@@ -192,10 +197,34 @@ global options:
 
     if [[ $REALIGN_BAM -eq 1 ]]
     then
-	echo "hi"
-    fi
+	REF="${@:${OPTIND}:1}"
+	IN_BAM="${@:$((${OPTIND}+1)):1}"
+	if [[ -z "$OUTPUT" ]]
+	then
+	    OUTPUT=`basename "$IN_BAM" ".bam"`
+	fi
 
-    if [[ INTERLEAVED -eq 1 ]]
+        # Check that the ref and bam files exist
+	if [[ -z "$REF" ]] || [[ ! -f "$REF" ]]
+	then
+            aln_usage
+            echo -e "Error: Reference file $REF not found.\n"
+            exit 1
+	elif [[ -z "$IN_BAM" ]] || [[ ! -e "$IN_BAM" ]]
+	then
+            aln_usage
+            echo -e "Error: BAM file $IN_BAM not found.\n"
+            exit 1
+	fi
+	mkdir -p $TEMP_DIR
+	if [[ ! -e $TEMP_DIR/fq_pipe ]]
+	then
+	    mkfifo $TEMP_DIR/fq_pipe
+	fi
+	FQ="$TEMP_DIR/fq_pipe"
+	samtools view -h -R <(echo "$REALIGN_RG") $IN_BAM | bam bam2Fastq --in - --merge  --unpairedOut /dev/null > $TEMP_DIR/fq_pipe &
+
+    elif [[ "$INTERLEAVED" -eq 1 ]]
     then
 	REF="${@:${OPTIND}:1}"
 	FQ="${@:$((${OPTIND}+1)):1}"
@@ -295,7 +324,7 @@ global options:
     fi
 
     # alignment command
-    if [[ $INTERLEAVED -eq 1 ]]
+    if [[ "$INTERLEAVED" -eq 1 ]] || [[ "$REALIGN_BAM" -eq 1 ]]
     then
 	if [[ $VERBOSE -eq 1 ]]
 	then
