updated var module to use VEP instead of SnpEff. currently slow though, because spools up one VEP instance for each freebayes thread. Plan to run forked VEP on whole file in next commit

diff --git a/bin/speedseq b/bin/speedseq
--- a/bin/speedseq
+++ b/bin/speedseq
@@ -23,6 +23,8 @@ function source_binaries() {
 	SNPEFF=
 	SNPEFF_CONFIG=
 	SNPEFF_GENOME=
+	VEP=`which variant_effect_predictor.pl || true`
+	VEP_CACHE_DIR="$HOME/.vep/"
 	BGZIP=`which bgzip || true`
 	TABIX=`which tabix || true`
 	LUMPY=`which lumpy || true`
@@ -340,7 +342,7 @@ options:
          -w FILE  BED file of windowed genomic intervals
          -t INT   threads [1]
          -T DIR   temp directory [./temp]
-         -A BOOL  annotate the vcf with snpEff (true or false) (default: true)
+         -A BOOL  annotate the vcf with VEP (true or false) (default: true)
          -K FILE  path to speedseq.config file (default: same directory as speedseq)
          -v       verbose
          -h       show this message
@@ -500,24 +502,77 @@ options:
     fi
     
     # call variants on each of the windows in parallel
-    if [[ $VERBOSE ]]
+    if [[ "$ANNOTATE" == "true" ]]
     then
-	echo -e "
-        $FREEBAYES \\
-            -f $REF \\
-            --region \$chrom:\$start..\$end \\
-            $BAM_STRING \\
-            > ${TEMP_DIR}/$OUTBASE.$i.vcf"
-    fi
 
-    for i in `cat $WINDOWS | awk '{print $1":"$2".."$3}'`
-    do
-	echo "$FREEBAYES \
-        -f $REF \
-        --region $i \
-        $BAM_STRING \
-        > ${TEMP_DIR}/$OUTBASE.$i.vcf"
-    done > $TEMP_DIR/var_command.txt
+	if [[ $VERBOSE ]]
+	then
+	    echo -e "
+            $FREEBAYES \\
+                -f $REF \\
+                --region \$chrom:\$start..\$end \\
+                $BAM_STRING \\
+                | $VEP \\
+                -o ${TEMP_DIR}/$OUTBASE.$i.vcf \\
+                --offline \\
+                --no_stats \\
+                --cache \\
+                --dir_cache $VEP_CACHE_DIR \
+                --species homo_sapiens \\
+                --sift b \\
+                --polyphen b \\
+                --symbol \\
+                --numbers \\
+                --biotype \\
+                --total_length \\
+                --vcf \\
+                --fields Consequence,Codons,Amino_acids,Gene,SYMBOL,Feature,EXON,PolyPhen,SIFT,Protein_position,BIOTYPE"
+	fi
+	
+	for i in `cat $WINDOWS | awk '{print $1":"$2".."$3}'`
+	do
+	    echo "$FREEBAYES \
+            -f $REF \
+            --region $i \
+            $BAM_STRING \
+            | $VEP \
+            -o ${TEMP_DIR}/$OUTBASE.$i.vcf \
+            --offline \
+            --no_stats \
+            --cache \
+            --dir_cache $VEP_CACHE_DIR \
+            --species homo_sapiens \
+            --sift b \
+            --polyphen b \
+            --symbol \
+            --numbers \
+            --biotype \
+            --total_length \
+            --vcf \
+            --fields Consequence,Codons,Amino_acids,Gene,SYMBOL,Feature,EXON,PolyPhen,SIFT,Protein_position,BIOTYPE"
+	done > $TEMP_DIR/var_command.txt
+
+    # if annotate is false:
+    else
+	if [[ $VERBOSE ]]
+	then
+            echo -e "
+            $FREEBAYES \\
+                -f $REF \\
+                --region \$chrom:\$start..\$end \\
+                $BAM_STRING \\
+                > ${TEMP_DIR}/$OUTBASE.$i.vcf"
+	fi
+
+	for i in `cat $WINDOWS | awk '{print $1":"$2".."$3}'`
+	do
+            echo "$FREEBAYES \
+            -f $REF \
+            --region $i \
+            $BAM_STRING \
+            > ${TEMP_DIR}/$OUTBASE.$i.vcf"
+	done > $TEMP_DIR/var_command.txt
+    fi
 
     # run the parallel freebayes command
     if [[ $VERBOSE ]]
@@ -536,42 +591,21 @@ options:
     fi
     grep "^#" $TEMP_DIR/$OUTBASE.$i.vcf > $TEMP_DIR/header.txt
 
-    if [[ "$ANNOTATE" == "true" ]]
+    # merge the vcf region files
+    if [[ $VERBOSE -eq 1 ]]
     then
-	# merge the vcf region files, with snpEff annotation
-	if [[ $VERBOSE -eq 1 ]]
-	then
-	    echo -e "
-        cat $TEMP_DIR/$OUTBASE.\"\$chrom:\$start..\$end\".vcf | grep -v \"^#\" \\
-            | $BEDTOOLS sort -i stdin | cat $TEMP_DIR/header.txt - \\
-            | $JAVA -jar $SNPEFF -c $SNPEFF_CONFIG -v $SNPEFF_GENOME \\
-            | $BGZIP -c > $OUTPUT.vcf.gz"
-	fi
-	for i in `cat $WINDOWS | awk '{print $1":"$2".."$3}'`
-        do
-            # if this fails then it bails out the script unless || true present
-	    cat $TEMP_DIR/$OUTBASE."$i".vcf | grep -v "^#" || true
-        done \
-            | $BEDTOOLS sort -i stdin | cat $TEMP_DIR/header.txt - \
-	    | $JAVA -jar $SNPEFF -c $SNPEFF_CONFIG -v $SNPEFF_GENOME \
-            | $BGZIP -c > $OUTPUT.vcf.gz
-    else
-        # merge the vcf region files, without snpEff annotation
-	if [[ $VERBOSE -eq 1 ]]
-	then
-	    echo -e "
+	echo -e "
         cat $TEMP_DIR/$OUTBASE.\"$chrom:\$start..\$end\".vcf | grep -v \"^#\" \\
             | $BEDTOOLS sort -i stdin | cat $TEMP_DIR/header.txt - \\
             | $BGZIP -c > $OUTPUT.vcf.gz"
-	fi
-        for i in `cat $WINDOWS | awk '{print $1":"$2".."$3}'`
-	do
-            # if this fails then it bails out the script
-	    cat $TEMP_DIR/$OUTBASE."$i".vcf | grep -v "^#" || true
-	done \
-	    | $BEDTOOLS sort -i stdin | cat $TEMP_DIR/header.txt - \
-	    | $BGZIP -c > $OUTPUT.vcf.gz
     fi
+    for i in `cat $WINDOWS | awk '{print $1":"$2".."$3}'`
+    do
+        # if this fails then it bails out the script
+	cat $TEMP_DIR/$OUTBASE."$i".vcf | grep -v "^#" || true
+    done \
+	| $BEDTOOLS sort -i stdin | cat $TEMP_DIR/header.txt - \
+	| $BGZIP -c > $OUTPUT.vcf.gz
 
     # index the vcf
     if [[ $VERBOSE -eq 1 ]]
