VEP annotation of SVs

diff --git a/bin/speedseq b/bin/speedseq
--- a/bin/speedseq
+++ b/bin/speedseq
@@ -978,6 +978,7 @@ sv options:
          -x FILE  BED file to exclude
          -g       genotype SV breakends with svtyper
          -d       calculate read-depth with CNVnator
+         -A BOOL  annotate the vcf with VEP (true or false) (default: true)
          -m INT   minimum weight for a call [4]
          -r FLOAT trim threshold [0]
          -L INT   read length [auto]
@@ -1016,6 +1017,7 @@ global options:
     SPEEDSEQ_DIR=`dirname $0`
     CONFIG="$SPEEDSEQ_DIR/speedseq.config"
     THREADS=1
+    ANNOTATE="true"
     MIN_WEIGHT=4
     TRIM_THRES=0
     EXCLUDE_BED=
@@ -1026,7 +1028,7 @@ global options:
     KEEP=0
     OUTPUT=""
 
-    while getopts ":hB:S:D:R:o:m:r:L:x:s:p:T:t:dgkvK:" OPTION
+    while getopts ":hB:S:D:R:o:m:r:L:x:s:p:T:t:A:dgkvK:" OPTION
     do
 	case "${OPTION}" in
             h)
@@ -1073,6 +1075,9 @@ global options:
 	    t)
 		THREADS="$OPTARG"
 		;;
+	    A)
+		ANNOTATE=`echo "$OPTARG" | tr [:upper:] [:lower:]`
+		;;
 	    d)
 		READDEPTH=1
 		;;
@@ -1116,15 +1121,20 @@ global options:
 	sv_usage
         echo -e "Error: sambamba executable not found. Please set path in $SPEEDSEQ_DIR/speedseq.config file\n"
         exit 1
-    elif [[ ! -f "$BGZIP" ]]
-    then
-        somatic_usage
-        echo -e "Error: bgzip executable not found. Please set path in $SPEEDSEQ_DIR/speedseq.config file\n"
-        exit 1
     elif [[ -z  "$BEDPETOVCF" ]]
     then
 	sv_usage
         echo -e "Error: bedpeToVcf executable not found. Please set path in $SPEEDSEQ_DIR/speedseq.config file\n"
+        exit 1
+    elif [[ ! -f "$VEP" ]] && [[ "$ANNOTATE" == "true" ]]
+    then
+	sv_usage
+        echo -e "Error: VEP not found. Please set path in $SPEEDSEQ_DIR/speedseq.config file\n"
+        exit 1
+    elif [[ ! -d "$VEP_CACHE_DIR" ]] && [[ "$ANNOTATE" == "true" ]]
+    then
+	sv_usage
+        echo -e "Error: VEP cache directory not found. Please set path in $SPEEDSEQ_DIR/speedseq.config file\n"
         exit 1
     fi
 
@@ -1191,6 +1201,14 @@ global options:
             exit 1
         fi
     done
+
+    # Check that ANNOTATE is either true or false
+    if [[ "$ANNOTATE" != "true" ]] && [[ "$ANNOTATE" != "false" ]]
+    then
+	sv_usage
+	echo -e "Error: -A must be either true or false\n"
+	exit 1
+    fi
 
     # default OUTPUT if not provided
     if test -z "$OUTPUT"
@@ -1279,11 +1297,11 @@ $LUMPY -t ${TEMP_DIR}/${OUTBASE} -mw $MIN_WEIGHT -tt $TRIM_THRES $EXCLUDE_BED_FM
         "
     fi
     # call lumpy
-    # $LUMPY -t ${TEMP_DIR}/${OUTBASE} -mw $MIN_WEIGHT -tt $TRIM_THRES \
-    # 	$EXCLUDE_BED_FMT \
-    # 	$LUMPY_DISC_STRING \
-    # 	$LUMPY_SPL_STRING \
-    # 	> $TEMP_DIR/$OUTBASE.sv.bedpe
+    $LUMPY -t ${TEMP_DIR}/${OUTBASE} -mw $MIN_WEIGHT -tt $TRIM_THRES \
+    	$EXCLUDE_BED_FMT \
+    	$LUMPY_DISC_STRING \
+    	$LUMPY_SPL_STRING \
+    	> $TEMP_DIR/$OUTBASE.sv.bedpe
 
     if [[ "$VERBOSE" -eq 1 ]]
     then
@@ -1398,40 +1416,101 @@ done
 
     # run cnvnator
     # WARNING: CNVNATOR currently only works on a single sample with one BAM file
-    if [[ READDEPTH -eq 1 ]]
+    if [[ "$READDEPTH" -eq 1 ]]
     then
+	echo "readdepth is $READDEPTH"
+
 	WINDOW_SIZE=100
 	SAMPLE=`cat $TEMP_DIR/$OUTBASE.sample.config | awk '{ print $1 }' | head -n 1`
 
 	if [[ "$VERBOSE" -eq 1 ]]
 	then
-	    echo "# run cnvnator-multi"
-	    echo "$CNVNATOR_WRAPPER --cnvnator $CNVNATOR_MULTI -T $TEMP_DIR/cnvnator-temp -t $THREADS -w 100 -b ${FULL_BAM_LIST[$i]} -o $TEMP_DIR/$OUTBASE.rd -c $CNVNATOR_CHROMS_DIR -g GRCh37
+	    echo "
+# run cnvnator-multi
+$CNVNATOR_WRAPPER --cnvnator $CNVNATOR_MULTI -T $TEMP_DIR/cnvnator-temp -t $THREADS -w 100 -b ${FULL_BAM_LIST[$i]} -o $TEMP_DIR/$OUTBASE.rd -c $CNVNATOR_CHROMS_DIR -g GRCh37
             "
 	fi
 	$CNVNATOR_WRAPPER --cnvnator $CNVNATOR_MULTI -T $TEMP_DIR/cnvnator-temp -t $THREADS -w 100 -b ${FULL_BAM_LIST[$i]} -o $TEMP_DIR/$OUTBASE.readdepth -c $CNVNATOR_CHROMS_DIR -g GRCh37
 
-	# annotate read-depth of LUMPY calls
+	# Calculate read-depth of LUMPY calls
 	if [[ "$VERBOSE" -eq 1 ]]
 	then
-	    echo "# annotate read-depth of LUMPY calls"
-	    echo "$ANNOTATE_RD --cnvnator $CNVNATOR_MULTI -s $SAMPLE -w $WINDOW_SIZE -r $TEMP_DIR/cnvnator-temp/${FULL_BAM_LIST[$i]}.hist.root -v $TEMP_DIR/$OUTBASE.sv.vcf > $TEMP_DIR/$OUTBASE.sv.rd.vcf
+	    echo "
+# Calculate read-depth of LUMPY calls
+$ANNOTATE_RD --cnvnator $CNVNATOR_MULTI -s $SAMPLE -w $WINDOW_SIZE -r $TEMP_DIR/cnvnator-temp/${FULL_BAM_LIST[$i]}.hist.root -v $TEMP_DIR/$OUTBASE.sv.vcf > $TEMP_DIR/$OUTBASE.sv.rd.vcf
             "
 	fi
-	$ANNOTATE_RD --cnvnator $CNVNATOR_MULTI -s $SAMPLE -w $WINDOW_SIZE -r $TEMP_DIR/cnvnator-temp/${FULL_BAM_LIST[$i]}.hist.root -v $TEMP_DIR/$OUTBASE.sv.vcf > $TEMP_DIR/$OUTBASE.sv.rd.vcf
-	mv $TEMP_DIR/$OUTBASE.sv.rd.vcf $TEMP_DIR/$OUTBASE.sv.vcf
+	$ANNOTATE_RD --cnvnator $CNVNATOR_MULTI -s $SAMPLE -w $WINDOW_SIZE -r $TEMP_DIR/cnvnator-temp/${FULL_BAM_LIST[$i]}.hist.root -v $TEMP_DIR/$OUTBASE.sv.vcf > $TEMP_DIR/$OUTBASE.rd.sv.vcf
+
+	if [[ "$VERBOSE" -eq 1 ]]
+	then
+	    echo "mv $TEMP_DIR/$OUTBASE.rd.sv.vcf $TEMP_DIR/$OUTBASE.rd.sv.vcf"
+	fi
+	mv $TEMP_DIR/$OUTBASE.rd.sv.vcf $TEMP_DIR/$OUTBASE.sv.vcf
     fi
 
-    # To do annotate
+    # Annotate structural variants with VEP
+    if [[ "$ANNOTATE" == "true" ]]
+    then
+	if [[ "$VERBOSE" -eq 1 ]]
+	then
+	    echo -e "
+# Annotate structural variants with VEP
+cat  $TEMP_DIR/$OUTBASE.sv.vcf \\
+    | awk '\$0~\"^#\" || \$5\!~\"[\\\\\[\\\\\]]\"' \\
+    | $VEP \\
+    --fork $THREADS \\
+    -o /dev/stdout \\
+    --force_overwrite \\
+    --offline \\
+    --no_stats \\
+    --cache \\
+    --dir_cache $VEP_CACHE_DIR \\
+    --species homo_sapiens \\
+    --sift b \\
+    --polyphen b \\
+    --symbol \\
+    --numbers \\
+    --biotype \\
+    --total_length \\
+    --vcf \\
+    --fields Consequence,Codons,Amino_acids,Gene,SYMBOL,Feature,EXON,PolyPhen,SIFT,Protein_position,BIOTYPE \\
+    | cat - <(cat $TEMP_DIR/$OUTBASE.sv.vcf | grep -v \"^#\" | awk '\$5~\"[\\\\\[\\\\\]]\"') \\
+    > $TEMP_DIR/$OUTBASE.vep.sv.vcf
+    "
+	fi
 
+	cat  $TEMP_DIR/$OUTBASE.sv.vcf \
+	    | awk '$0~"^#" || $5!~"[\\[\\]]"' \
+	    | $VEP \
+            --fork $THREADS \
+            -o /dev/stdout \
+            --force_overwrite \
+            --offline \
+            --no_stats \
+            --cache \
+            --dir_cache $VEP_CACHE_DIR \
+            --species homo_sapiens \
+            --sift b \
+            --polyphen b \
+            --symbol \
+            --numbers \
+            --biotype \
+            --total_length \
+            --vcf \
+            --fields Consequence,Codons,Amino_acids,Gene,SYMBOL,Feature,EXON,PolyPhen,SIFT,Protein_position,BIOTYPE \
+	    | cat - <(cat $TEMP_DIR/$OUTBASE.sv.vcf | grep -v "^#" | awk '$5~"[\\[\\]]"') \
+	    > $TEMP_DIR/$OUTBASE.vep.sv.vcf
 
+	mv $TEMP_DIR/$OUTBASE.vep.sv.vcf $TEMP_DIR/$OUTBASE.sv.vcf
+    fi
 
     # write output
-    mv $TEMP_DIR/$OUTBASE.sv.bedpe $OUTPUT.sv.bedpe
-    mv $TEMP_DIR/$OUTBASE.sv.vcf $OUTPUT.sv.vcf
+    cp $TEMP_DIR/$OUTBASE.sv.bedpe $OUTPUT.sv.bedpe
+    cp $TEMP_DIR/$OUTBASE.sv.vcf $OUTPUT.sv.vcf
 
     # clean up
-    if [[ $KEEP -eq 0 ]]
+    if [[ "$KEEP" -eq 0 ]]
     then
 	rm -r ${TEMP_DIR}
     fi
