lumpy express features to call SVs on BWA MEM aligned BAM without pre-extracting splitters and discordants

diff --git a/bin/speedseq b/bin/speedseq
--- a/bin/speedseq
+++ b/bin/speedseq
@@ -44,6 +44,7 @@ function source_binaries() {
 	BEDPETOVCF=`which bedpeToVcf || true`
 	LUMPYTOBEDPE=`which lumpyToBedpe || true`
 	SVTYPER=`which svtyper || true`
+	BAMGROUPREADS=`which bamgroupreads.py || true`
 
         # CNVnator
 	CNVNATOR_WRAPPER=`which cnvnator_wrapper.py || true`
@@ -1200,6 +1201,8 @@ global options:
     VERBOSE=0
     KEEP=0
     OUTPUT=""
+    MAX_SPLIT_COUNT=2
+    MIN_NON_OVERLAP=20
 
     while getopts ":hB:S:D:R:o:m:r:L:x:s:p:T:t:A:dgkvK:" OPTION
     do
@@ -1314,8 +1317,12 @@ global options:
 	sv_usage
         echo -e "Error: vawk executable not found. Please set path in $SPEEDSEQ_DIR/speedseq.config file\n"
         exit 1
+    elif [[ -z  "$SAMBLASTER" ]] && [[ -z "${DISC_BAM_STRING}${SPL_BAM_STRING}" ]]
+    then
+	sv_usage
+        echo -e "Error: samblaster executable not found. Please set path in $SPEEDSEQ_DIR/speedseq.config file\n"
+        exit 1
     fi
-
 
     # if genotyping requested, look for svtyper
     if [[ "$GENOTYPE" -eq 1 ]] && [[ -z "$SVTYPER" ]]
@@ -1362,17 +1369,21 @@ global options:
 	echo -e "Error: reference fasta file $REF not indexed\n"
 	exit 1
     fi
-    if [[ ${#FULL_BAM_LIST[@]} -eq 0 ]] || [[ ${#SPL_BAM_LIST[@]} -eq 0 ]] || [[ ${#DISC_BAM_LIST[@]} -eq 0 ]]
+    if [[ ${#FULL_BAM_LIST[@]} -eq 0 ]]
     then
 	sv_usage
-	echo -e "Error: -B, -S, and -D are required\n"
+	echo -e "Error: -B is required\n"
 	exit 1
     fi
-    if [[ ! ${#FULL_BAM_LIST[@]} -eq ${#SPL_BAM_LIST[@]} ]] || [[ ! ${#FULL_BAM_LIST[@]} -eq ${#DISC_BAM_LIST[@]} ]]
+
+    if [[ ! -z "$SPL_BAM_STRING" ]] && [[ ! -z "$DISC_BAM_STRING" ]]
     then
-	sv_usage
-	echo -e "Error: -B, -S, and -D arguments have different lengths\n"
-	exit 1
+	if [[ ! ${#FULL_BAM_LIST[@]} -eq ${#SPL_BAM_LIST[@]} ]] || [[ ! ${#FULL_BAM_LIST[@]} -eq ${#DISC_BAM_LIST[@]} ]]
+	then
+	    sv_usage
+	    echo -e "Error: -B, -S, and -D arguments have different lengths\n"
+	    exit 1
+	fi
     fi
     for TEST_BAM in ${FULL_BAM_LIST[@]} ${SPL_BAM_LIST[@]} ${DISC_BAM_LIST[@]}
     do
@@ -1412,83 +1423,205 @@ global options:
 	mkdir -p $TEMP_DIR	
     fi
 
-    # create the LUMPY config file for generating the VCF
-    for i in $( seq 0 $(( ${#FULL_BAM_LIST[@]}-1 )) )
-    do
-        FULL_BAM=${FULL_BAM_LIST[$i]}
-        SPL_BAM=${SPL_BAM_LIST[$i]}
-        DISC_BAM=${DISC_BAM_LIST[$i]}
-
-	FULL_SAMPLE=`$SAMBAMBA view -H $FULL_BAM | grep -m 1 "^@RG" | awk -v i=$i '{ for (j=1;j<=NF;++j) {if ($j~"^SM:") { gsub("^SM:","",$j); print $j } } }'`
-	SPL_SAMPLE=`$SAMBAMBA view -H $SPL_BAM | grep -m 1 "^@RG" | awk -v i=$i '{ for (j=1;j<=NF;++j) {if ($j~"^SM:") { gsub("^SM:","",$j); print $j } } }'`
-	DISC_SAMPLE=`$SAMBAMBA view -H $DISC_BAM | grep -m 1 "^@RG" | awk -v i=$i '{ for (j=1;j<=NF;++j) {if ($j~"^SM:") { gsub("^SM:","",$j); print $j } } }'`
-
-	echo -e "$DISC_SAMPLE\t$(($i+1))0\tPE\t$DISC_BAM"
-	echo -e "$SPL_SAMPLE\t$(($i+1))1\tSR\t$SPL_BAM"
-	echo -e "$FULL_SAMPLE\t$(($i+1))2\tRD\t$FULL_BAM"
-	
-    done > $TEMP_DIR/$OUTBASE.sample.config
-
-    # if LUMPY_SPL_STRING not provided, make one
-    if test -z "$LUMPY_SPL_STRING"
+    # If splitter and discordant BAMs not provided, generate them
+    # (LUMPY express)
+    if [[ -z "${SPL_BAM_LIST}${DISC_BAM_LIST}" ]]
     then
+	# initialize split and discordant bam lists
+	SPL_BAM_LIST=()
+	DISC_BAM_LIST=()
+
+	# create temp files and pipes
+	mkdir -p $TEMP_DIR/spl $TEMP_DIR/disc
+	if [[ ! -e $TEMP_DIR/spl_pipe ]]
+	then
+	    mkfifo $TEMP_DIR/spl_pipe
+	fi
+	if [[ ! -e $TEMP_DIR/disc_pipe ]]
+	then
+	    mkfifo $TEMP_DIR/disc_pipe
+	fi
+
+        # generate histo files and construct the strings for LUMPY
 	for i in $( seq 0 $(( ${#FULL_BAM_LIST[@]}-1 )) )
 	do
             FULL_BAM=${FULL_BAM_LIST[$i]}
-            SPL_BAM=${SPL_BAM_LIST[$i]}
-            DISC_BAM=${DISC_BAM_LIST[$i]}
-	    
-            FULL_BASE=`basename "$FULL_BAM"`
-            SPL_BASE=`basename "$SPL_BAM"`
-            DISC_BASE=`basename "$DISC_BAM"`
 
-	    LUMPY_SPL_STRING="$LUMPY_SPL_STRING -sr bam_file:${SPL_BAM},back_distance:10,min_mapping_threshold:20,weight:1,id:$(($i+1))1,min_clip:20"
+	    # calc readlength if not provided
+	    READ_LENGTH=`$SAMBAMBA view $FULL_BAM | head -n 10000 | awk 'BEGIN { MAX_LEN=0 } { LEN=length($10); if (LEN>MAX_LEN) MAX_LEN=LEN } END { print MAX_LEN }'`
+
+	    # parse the libraries in the BAM header to extract readgroups from the same library
+	    LIB_RG_LIST=(`$SAMBAMBA view -H $FULL_BAM \
+		| grep "^@RG" \
+		| awk \
+		    '{
+			for (j=1;j<=NF;++j) {
+			    if ($j~"^ID") {
+				id=$j
+				gsub("^ID:","",id)
+			    }
+			    else if ($j~"^LB:") {
+				lib=$j
+				gsub("^LB:","",lib);
+			    }
+			}
+			lib_list[lib][length(lib_list[lib])+1] = id
+		    }
+		    END {
+			for (i in lib_list) {
+			    RG_STRING=lib_list[i][1]
+			    for (j=2;j<=length(lib_list[i]);++j) {
+				RG_STRING=RG_STRING","lib_list[i][j]
+			    }
+			    print RG_STRING
+			}
+		    }'`)
+
+	    for j in $( seq 0 $(( ${#LIB_RG_LIST[@]}-1 )) )
+	    do
+		RG_STRING=${LIB_RG_LIST[$j]}
+		if [[ "$VERBOSE" -eq 1 ]]
+		then
+		    echo -e "
+		$PYTHON27 $BAMGROUPREADS -i $FULL_BAM -r $RG_STRING \\
+		    | $SAMBLASTER --acceptDupMarks --excludeDups --addMateTags --maxSplitCount $MAX_SPLIT_COUNT --minNonOverlap $MIN_NON_OVERLAP \\
+			--splitterFile $TEMP_DIR/spl_pipe --discordantFile $TEMP_DIR/disc_pipe \\
+		    | $SAMBAMBA view -S -F 'paired and mate_is_reverse_strand and not (unmapped or mate_is_unmapped or reverse_strand or secondary_alignment or duplicate)' /dev/stdin \\
+		    | awk '{ if (NR<=1000000) print > \"/dev/stdout\" ; else print > \"/dev/null\" }' \\
+		    | $PYTHON27 $PAIREND_DISTRO -r $READ_LENGTH -X 4 -N 1000000 -o ${TEMP_DIR}/$OUTBASE.sample$(($i+1)).lib$(($j+1)).x4.histo \\
+		    > ${TEMP_DIR}/$OUTBASE.sample$(($i+1)).lib$(($j+1)).insert.stats
+
+		$SAMBAMBA view -S -f bam -l 0 $TEMP_DIR/spl_pipe \\
+		    | $SAMBAMBA sort -m 1G --tmpdir=$TEMP_DIR/spl -o $TEMP_DIR/$OUTBASE.sample$(($i+1)).lib$(($j+1)).splitters.bam /dev/stdin
+		$SAMBAMBA view -S -f bam -l 0 $TEMP_DIR/disc_pipe \\
+		    | $SAMBAMBA sort -m 1G --tmpdir=$TEMP_DIR/disc -o $TEMP_DIR/$OUTBASE.sample$(($i+1)).lib$(($j+1)).discordants.bam /dev/stdin"
+		fi
+
+		echo -e "
+                $PYTHON27 $BAMGROUPREADS -i $FULL_BAM -r $RG_STRING \
+		    | $SAMBLASTER --acceptDupMarks --excludeDups --addMateTags --maxSplitCount $MAX_SPLIT_COUNT --minNonOverlap $MIN_NON_OVERLAP \
+		        --splitterFile $TEMP_DIR/spl_pipe --discordantFile $TEMP_DIR/disc_pipe \
+                    | $SAMBAMBA view -S -F 'paired and mate_is_reverse_strand and not (unmapped or mate_is_unmapped or reverse_strand or secondary_alignment or duplicate)' /dev/stdin \
+                    | awk '{ if (NR<=1000000) print > \"/dev/stdout\" ; else print > \"/dev/null\" }' \
+		    | $PYTHON27 $PAIREND_DISTRO -r $READ_LENGTH -X 4 -N 1000000 -o ${TEMP_DIR}/$OUTBASE.sample$(($i+1)).lib$(($j+1)).x4.histo \
+		    > ${TEMP_DIR}/$OUTBASE.sample$(($i+1)).lib$(($j+1)).insert.stats
+
+		$SAMBAMBA view -S -f bam -l 0 $TEMP_DIR/spl_pipe \
+		    | $SAMBAMBA sort -m 1G --tmpdir=$TEMP_DIR/spl -o $TEMP_DIR/$OUTBASE.sample$(($i+1)).lib$(($j+1)).splitters.bam /dev/stdin
+		$SAMBAMBA view -S -f bam -l 0 $TEMP_DIR/disc_pipe \
+		    | $SAMBAMBA sort -m 1G --tmpdir=$TEMP_DIR/disc -o $TEMP_DIR/$OUTBASE.sample$(($i+1)).lib$(($j+1)).discordants.bam /dev/stdin" \
+		    | $PARALLEL -j 3
+
+		HISTO_LIST+=(${TEMP_DIR}/$OUTBASE.sample$(($i+1)).lib$(($j+1)).x4.histo)
+		SPL_BAM_LIST+=($TEMP_DIR/$OUTBASE.sample$(($i+1)).lib$(($j+1)).splitters.bam)
+		DISC_BAM_LIST+=($TEMP_DIR/$OUTBASE.sample$(($i+1)).lib$(($j+1)).discordants.bam)
+
+		# generate discordant pair string for LUMPY
+		MEAN=`cat ${TEMP_DIR}/$OUTBASE.sample$(($i+1)).lib$(($j+1)).insert.stats | tr '\t' '\n' | grep "^mean" | sed 's/mean\://g'`
+		STDEV=`cat ${TEMP_DIR}/$OUTBASE.sample$(($i+1)).lib$(($j+1)).insert.stats | tr '\t' '\n' | grep "^stdev" | sed 's/stdev\://g'`
+		LUMPY_DISC_STRING="$LUMPY_DISC_STRING -pe bam_file:$TEMP_DIR/$OUTBASE.sample$(($i+1)).lib$(($j+1)).discordants.bam,histo_file:${TEMP_DIR}/$OUTBASE.sample$(($i+1)).lib$(($j+1)).x4.histo,mean:${MEAN},stdev:${STDEV},read_length:${READ_LENGTH},min_non_overlap:${READ_LENGTH},discordant_z:5,back_distance:10,weight:1,id:$(($i+1))$(($j+1))0,min_mapping_threshold:20"
+
+		# generate split-read string for LUMPY
+		LUMPY_SPL_STRING="$LUMPY_SPL_STRING -sr bam_file:${TEMP_DIR}/$OUTBASE.sample$(($i+1)).lib$(($j+1)).splitters.bam,back_distance:10,min_mapping_threshold:20,weight:1,id:$(($i+1))$(($j+1))1,min_clip:20"
+
+		# generate LUMPY sample config file
+		DISC_BAM=$TEMP_DIR/$OUTBASE.sample$(($i+1)).lib$(($j+1)).discordants.bam
+		SPL_BAM=${TEMP_DIR}/$OUTBASE.sample$(($i+1)).lib$(($j+1)).splitters.bam
+		DISC_SAMPLE=`$SAMBAMBA view -H $DISC_BAM | grep -m 1 "^@RG" | awk -v i=$i '{ for (j=1;j<=NF;++j) {if ($j~"^SM:") { gsub("^SM:","",$j); print $j } } }'`
+		SPL_SAMPLE=`$SAMBAMBA view -H $SPL_BAM | grep -m 1 "^@RG" | awk -v i=$i '{ for (j=1;j<=NF;++j) {if ($j~"^SM:") { gsub("^SM:","",$j); print $j } } }'`
+		echo -e "$DISC_SAMPLE\t$(($i+1))$(($j+1))0\tPE\t$DISC_BAM" >> $TEMP_DIR/$OUTBASE.sample.config
+		echo -e "$SPL_SAMPLE\t$(($i+1))$(($j+1))1\tSR\t$SPL_BAM" >> $TEMP_DIR/$OUTBASE.sample.config
+	    done
 	done
-    fi
 
-    # if LUMPY_DISC_STRING not provided, make one
-    if test -z "$LUMPY_DISC_STRING"
-    then
-	echo -n "Calculating alignment stats... "
+	# check that splitters and discordants were generated properly
+	if [[ ! ${#HISTO_LIST[@]} -eq ${#DISC_BAM_LIST[@]} ]] || [[ ! ${#SPL_BAM_LIST[@]} -eq ${#DISC_BAM_LIST[@]} ]]
+	then
+	    sv_usage
+	    echo -e "Error: could not generate splitters and discordants\n"
+	    exit 1
+	fi
+
+    # else (user provided a splitter and discordants file)
+    else
+	# create the LUMPY config file for generating the VCF
 	for i in $( seq 0 $(( ${#FULL_BAM_LIST[@]}-1 )) )
 	do
-            FULL_BAM=${FULL_BAM_LIST[$i]}
-            SPL_BAM=${SPL_BAM_LIST[$i]}
-            DISC_BAM=${DISC_BAM_LIST[$i]}
-	    
-            FULL_BASE=`basename "$FULL_BAM"`
-            SPL_BASE=`basename "$SPL_BAM"`
-            DISC_BASE=`basename "$DISC_BAM"`
-	    
-            # calc readlength if not provided
-            if test -z "$READ_LENGTH"
-            then
-		READ_LENGTH=`$SAMBAMBA view $FULL_BAM | head -n 10000 | awk 'BEGIN { MAX_LEN=0 } { LEN=length($10); if (LEN>MAX_LEN) MAX_LEN=LEN } END { print MAX_LEN }'`
-            fi
+	    FULL_BAM=${FULL_BAM_LIST[$i]}
+	    SPL_BAM=${SPL_BAM_LIST[$i]}
+	    DISC_BAM=${DISC_BAM_LIST[$i]}
 
-	    if [[ "VERBOSE" -eq 1 ]]
-	    then
-		echo "
-# calculate stats
-$SAMBAMBA view -F \"paired and mate_is_reverse_strand and not (unmapped or mate_is_unmapped or reverse_strand or secondary_alignment or duplicate)\" $FULL_BAM \\
-    | head -n 10000000 | tail -n 1000000 \\
-    | $PAIREND_DISTRO -r $READ_LENGTH -X 4 -N 1000000 -o ${TEMP_DIR}/$FULL_BASE.x4.histo \\
-    > ${TEMP_DIR}/$FULL_BASE.insert.stats
-	    "
-	    fi
+	    FULL_SAMPLE=`$SAMBAMBA view -H $FULL_BAM | grep -m 1 "^@RG" | awk -v i=$i '{ for (j=1;j<=NF;++j) {if ($j~"^SM:") { gsub("^SM:","",$j); print $j } } }'`
+	    SPL_SAMPLE=`$SAMBAMBA view -H $SPL_BAM | grep -m 1 "^@RG" | awk -v i=$i '{ for (j=1;j<=NF;++j) {if ($j~"^SM:") { gsub("^SM:","",$j); print $j } } }'`
+	    DISC_SAMPLE=`$SAMBAMBA view -H $DISC_BAM | grep -m 1 "^@RG" | awk -v i=$i '{ for (j=1;j<=NF;++j) {if ($j~"^SM:") { gsub("^SM:","",$j); print $j } } }'`
 
-            # calculate stats
-            $SAMBAMBA view -F "paired and mate_is_reverse_strand and not (unmapped or mate_is_unmapped or reverse_strand or secondary_alignment or duplicate)" $FULL_BAM \
-		| head -n 10000000 | tail -n 1000000 \
-		| $PAIREND_DISTRO -r $READ_LENGTH -X 4 -N 1000000 -o ${TEMP_DIR}/$FULL_BASE.x4.histo \
-		> ${TEMP_DIR}/$FULL_BASE.insert.stats
-	    
-            MEAN=`cat ${TEMP_DIR}/$FULL_BASE.insert.stats | tr '\t' '\n' | grep "^mean" | sed 's/mean\://g'`
-            STDEV=`cat ${TEMP_DIR}/$FULL_BASE.insert.stats | tr '\t' '\n' | grep "^stdev" | sed 's/stdev\://g'`
+	    echo -e "$DISC_SAMPLE\t$(($i+1))0\tPE\t$DISC_BAM"
+	    echo -e "$SPL_SAMPLE\t$(($i+1))1\tSR\t$SPL_BAM"
+	    echo -e "$FULL_SAMPLE\t$(($i+1))2\tRD\t$FULL_BAM"
 
-	    LUMPY_DISC_STRING="$LUMPY_DISC_STRING -pe bam_file:${DISC_BAM},histo_file:${TEMP_DIR}/${FULL_BASE}.x4.histo,mean:${MEAN},stdev:${STDEV},read_length:${READ_LENGTH},min_non_overlap:${READ_LENGTH},discordant_z:5,back_distance:10,weight:1,id:$(($i+1))0,min_mapping_threshold:20"
-	done
-	echo "done"
+	done > $TEMP_DIR/$OUTBASE.sample.config
+
+	# if LUMPY_SPL_STRING not provided, make one
+	if test -z "$LUMPY_SPL_STRING"
+	then
+	    for i in $( seq 0 $(( ${#FULL_BAM_LIST[@]}-1 )) )
+	    do
+		FULL_BAM=${FULL_BAM_LIST[$i]}
+		SPL_BAM=${SPL_BAM_LIST[$i]}
+		DISC_BAM=${DISC_BAM_LIST[$i]}
+
+		FULL_BASE=`basename "$FULL_BAM"`
+		SPL_BASE=`basename "$SPL_BAM"`
+		DISC_BASE=`basename "$DISC_BAM"`
+
+		LUMPY_SPL_STRING="$LUMPY_SPL_STRING -sr bam_file:${SPL_BAM},back_distance:10,min_mapping_threshold:20,weight:1,id:$(($i+1))1,min_clip:20"
+	    done
+	fi
+
+	# if LUMPY_DISC_STRING not provided, make one
+	if test -z "$LUMPY_DISC_STRING"
+	then
+	    echo -n "Calculating alignment stats... "
+	    for i in $( seq 0 $(( ${#FULL_BAM_LIST[@]}-1 )) )
+	    do
+		FULL_BAM=${FULL_BAM_LIST[$i]}
+		SPL_BAM=${SPL_BAM_LIST[$i]}
+		DISC_BAM=${DISC_BAM_LIST[$i]}
+
+		FULL_BASE=`basename "$FULL_BAM"`
+		SPL_BASE=`basename "$SPL_BAM"`
+		DISC_BASE=`basename "$DISC_BAM"`
+
+		# calc readlength if not provided
+		if test -z "$READ_LENGTH"
+		then
+		    READ_LENGTH=`$SAMBAMBA view $FULL_BAM | head -n 10000 | awk 'BEGIN { MAX_LEN=0 } { LEN=length($10); if (LEN>MAX_LEN) MAX_LEN=LEN } END { print MAX_LEN }'`
+		fi
+
+		if [[ "VERBOSE" -eq 1 ]]
+		then
+		    echo "
+    # calculate stats
+    $SAMBAMBA view -F \"paired and mate_is_reverse_strand and not (unmapped or mate_is_unmapped or reverse_strand or secondary_alignment or duplicate)\" $FULL_BAM \\
+	| head -n 10000000 | tail -n 1000000 \\
+	| $PAIREND_DISTRO -r $READ_LENGTH -X 4 -N 1000000 -o ${TEMP_DIR}/$FULL_BASE.x4.histo \\
+	> ${TEMP_DIR}/$FULL_BASE.insert.stats
+		"
+		fi
+
+		# calculate stats
+		$SAMBAMBA view -F "paired and mate_is_reverse_strand and not (unmapped or mate_is_unmapped or reverse_strand or secondary_alignment or duplicate)" $FULL_BAM \
+		    | head -n 10000000 | tail -n 1000000 \
+		    | $PAIREND_DISTRO -r $READ_LENGTH -X 4 -N 1000000 -o ${TEMP_DIR}/$FULL_BASE.x4.histo \
+		    > ${TEMP_DIR}/$FULL_BASE.insert.stats
+
+		MEAN=`cat ${TEMP_DIR}/$FULL_BASE.insert.stats | tr '\t' '\n' | grep "^mean" | sed 's/mean\://g'`
+		STDEV=`cat ${TEMP_DIR}/$FULL_BASE.insert.stats | tr '\t' '\n' | grep "^stdev" | sed 's/stdev\://g'`
+
+		LUMPY_DISC_STRING="$LUMPY_DISC_STRING -pe bam_file:${DISC_BAM},histo_file:${TEMP_DIR}/${FULL_BASE}.x4.histo,mean:${MEAN},stdev:${STDEV},read_length:${READ_LENGTH},min_non_overlap:${READ_LENGTH},discordant_z:5,back_distance:10,weight:1,id:$(($i+1))0,min_mapping_threshold:20"
+	    done
+	    echo "done"
+	fi
     fi
 
     echo "Running LUMPY... "
@@ -1912,7 +2045,7 @@ global options:
     then
 	REALIGN_RG_LIST=(`$SAMBAMBA view -H $IN_BAM \
 	    | grep "^@RG" \
-	    | awk -v i=$i \
+	    | awk \
 		'{
 		    for (j=1;j<=NF;++j) {
 			if ($j~"^ID") {
