lumpy can analyze multiple samples at once

diff --git a/bin/speedseq b/bin/speedseq
--- a/bin/speedseq
+++ b/bin/speedseq
@@ -410,8 +410,6 @@ options:
 	fi
     done
 
-    echo $BAM_STRING
-
     echo "Calling variants..."
 
     # make temporary directory
@@ -696,9 +694,9 @@ function lumpy() {
 usage:   speedseq lumpy [options]
 
 lumpy options:
-         -B FILE  full BAM file (required)
-         -S FILE  split reads BAM file (required)
-         -D FILE  discordant reads BAM file (required)
+         -B FILE  full BAM file(s) (comma separated) (required)
+         -S FILE  split reads BAM file(s) (comma separated, order as in -B) (required)
+         -D FILE  discordant reads BAM files(s) (comma separated, order as in -B) (required)
          -o STR   output prefix [fullBam.bam]
          -x FILE  BED file to exclude
          -m INT   minimum weight for a call [4]
@@ -751,13 +749,13 @@ global options:
                 exit 1
                 ;;
 	    B)
-		FULL_BAM="$OPTARG"
+		FULL_BAM_STRING="$OPTARG"
 		;;
 	    S)
-		SPL_BAM="$OPTARG"
+		SPL_BAM_STRING="$OPTARG"
 		;;
 	    D)
-		DISC_BAM="$OPTARG"
+		DISC_BAM_STRING="$OPTARG"
 		;;
             o)
                 OUTPUT="$OPTARG"
@@ -776,10 +774,10 @@ global options:
 		EXCLUDE_BED_FMT="-x $EXCLUDE_BED"
 		;;  
 	    s)
-		LUMPY_SPL_STRING="$OPTARG"
+		LUMPY_SPL_STRING="-sr $OPTARG"
 		;;
 	    p)
-		LUMPY_DISC_STRING="$OPTARG"
+		LUMPY_DISC_STRING="-pe $OPTARG"
 		;;
             T)
                 TEMP_DIR="$OPTARG"
@@ -792,7 +790,36 @@ global options:
 		;;
 	esac
     done
+
+    # parse the BAM strings
+    FULL_BAM_LIST=(`echo $FULL_BAM_STRING | tr "," " "`)
+    SPL_BAM_LIST=(`echo $SPL_BAM_STRING | tr "," " "`)
+    DISC_BAM_LIST=(`echo $DISC_BAM_STRING | tr "," " "`)
+
     OPTIND=0
+
+    # Check that the bam files exist
+    if [[ ${#FULL_BAM_LIST[@]} -eq 0 ]] || [[ ${#SPL_BAM_LIST[@]} -eq 0 ]] || [[ ${#DISC_BAM_LIST[@]} -eq 0 ]]
+    then
+	lumpy_usage
+	echo -e "Error: -B, -S, and -D are required\n"
+	exit 1
+    fi
+    if [[ ! ${#FULL_BAM_LIST[@]} -eq ${#SPL_BAM_LIST[@]} ]] || [[ ! ${#FULL_BAM_LIST[@]} -eq ${#DISC_BAM_LIST[@]} ]]
+    then
+	lumpy_usage
+	echo -e "Error: -B, -S, and -D arguments have different lengths\n"
+	exit 1
+    fi
+    for TEST_BAM in ${FULL_BAM_LIST[@]} ${SPL_BAM_LIST[@]} ${DISC_BAM_LIST[@]}
+    do
+        if [[ ! -f $TEST_BAM ]]
+        then
+            lumpy_usage
+            echo -e "Error: BAM file $TEST_BAM not found.\n"
+            exit 1
+        fi
+    done
 
     # Check the for the relevant binaries
     source_binaries $CONFIG
@@ -814,59 +841,75 @@ global options:
         exit 1
     fi
 
-    echo "Running LUMPY..."
-
-    # error-check input
-    if [[ ! -f $FULL_BAM ]] || [[ ! -f $SPL_BAM ]] || [[ ! -f $DISC_BAM ]]
-    then
-	lumpy_usage
-	exit 1
-    fi
-
     # default OUTPUT if not provided
     if test -z "$OUTPUT"
     then
-    OUTPUT=`basename "$FULL_BAM"`
+	OUTPUT=`basename "$FULL_BAM"`
     fi
-
     OUTBASE=`basename "$OUTPUT"`
 
     # make temporary directory
-    mkdir ${TEMP_DIR}
-
-    # calc readlength if not provided
-    if test -z "$READ_LENGTH"
-    then
-	READ_LENGTH=`$SAMBAMBA view $FULL_BAM | head -n 10000 | awk 'BEGIN { MAX_LEN=0 } { LEN=length($10); if (LEN>MAX_LEN) MAX_LEN=LEN } END { print MAX_LEN }'`
-    fi
-
-    # calculate stats
-    echo -n "Calculating alignment stats... "
-    $SAMBAMBA view -F "not secondary_alignment" $FULL_BAM \
-	| head -n 10000000 | tail -n 5000000 \
-	| $PAIREND_DISTRO -rl $READ_LENGTH -X 3 -N 1000000 -o ${TEMP_DIR}/$OUTBASE.x3.histo \
-	> ${TEMP_DIR}/$OUTBASE.insert.stats
-    echo "done"
-    MEAN=`cat ${TEMP_DIR}/$OUTBASE.insert.stats | tr '\t' '\n' | grep "^mean" | sed 's/mean\://g'`
-    STDEV=`cat ${TEMP_DIR}/$OUTBASE.insert.stats | tr '\t' '\n' | grep "^stdev" | sed 's/stdev\://g'`
+    mkdir -p ${TEMP_DIR}
 
     # if LUMPY_SPL_STRING not provided, make one
     if test -z "$LUMPY_SPL_STRING"
     then
-	LUMPY_SPL_STRING="bam_file:${SPL_BAM},back_distance:20,min_mapping_threshold:20,weight:1,id:11,min_clip:20"
+	for i in $( seq 0 $(( ${#FULL_BAM_LIST[@]}-1 )) )
+	do
+            FULL_BAM=${FULL_BAM_LIST[$i]}
+            SPL_BAM=${SPL_BAM_LIST[$i]}
+            DISC_BAM=${DISC_BAM_LIST[$i]}
+	    
+            FULL_BASE=`basename "$FULL_BAM"`
+            SPL_BASE=`basename "$SPL_BAM"`
+            DISC_BASE=`basename "$DISC_BAM"`
+
+	    LUMPY_SPL_STRING="$LUMPY_SPL_STRING -sr bam_file:${SPL_BAM},back_distance:20,min_mapping_threshold:20,weight:1,id:$(($i+1))1,min_clip:20"
+	done
     fi
 
     # if LUMPY_DISC_STRING not provided, make one
     if test -z "$LUMPY_DISC_STRING"
     then
-	LUMPY_DISC_STRING="bam_file:${DISC_BAM},histo_file:${TEMP_DIR}/${OUTPUT}.x3.histo,mean:${MEAN},stdev:${STDEV},read_length:${READ_LENGTH},min_non_overlap:${READ_LENGTH},discordant_z:5,back_distance:20,weight:1,id:10,min_mapping_threshold:20"
+	echo -n "Calculating alignment stats... "
+	for i in $( seq 0 $(( ${#FULL_BAM_LIST[@]}-1 )) )
+	do
+            FULL_BAM=${FULL_BAM_LIST[$i]}
+            SPL_BAM=${SPL_BAM_LIST[$i]}
+            DISC_BAM=${DISC_BAM_LIST[$i]}
+	    
+            FULL_BASE=`basename "$FULL_BAM"`
+            SPL_BASE=`basename "$SPL_BAM"`
+            DISC_BASE=`basename "$DISC_BAM"`
+	    
+            # calc readlength if not provided
+            if test -z "$READ_LENGTH"
+            then
+		READ_LENGTH=`$SAMBAMBA view $FULL_BAM | head -n 10000 | awk 'BEGIN { MAX_LEN=0 } { LEN=length($10); if (LEN>MAX_LEN) MAX_LEN=LEN } END { print MAX_LEN }'`
+            fi
+	    
+            # calculate stats
+            $SAMBAMBA view -F "not secondary_alignment" $FULL_BAM \
+		| head -n 10000000 | tail -n 5000000 \
+		| $PAIREND_DISTRO -rl $READ_LENGTH -X 3 -N 1000000 -o ${TEMP_DIR}/$FULL_BASE.x3.histo \
+		> ${TEMP_DIR}/$FULL_BASE.insert.stats
+	    
+            MEAN=`cat ${TEMP_DIR}/$FULL_BASE.insert.stats | tr '\t' '\n' | grep "^mean" | sed 's/mean\://g'`
+            STDEV=`cat ${TEMP_DIR}/$FULL_BASE.insert.stats | tr '\t' '\n' | grep "^stdev" | sed 's/stdev\://g'`
+
+	    LUMPY_DISC_STRING="$LUMPY_DISC_STRING -pe bam_file:${DISC_BAM},histo_file:${TEMP_DIR}/${FULL_BASE}.x3.histo,mean:${MEAN},stdev:${STDEV},read_length:${READ_LENGTH},min_non_overlap:${READ_LENGTH},discordant_z:5,back_distance:20,weight:1,id:$(($i+1))0,min_mapping_threshold:20"
+	done
+	echo "done"
     fi
 
+    echo -n "Running LUMPY... "
     # call lumpy
-    $LUMPY -t ${TEMP_DIR}/${OUTBASE} -mw $MIN_WEIGHT -tt $TRIM_THRES $EXCLUDE_BED_FMT \
-	-pe $LUMPY_DISC_STRING \
-	-sr $LUMPY_SPL_STRING \
+    $LUMPY -t ${TEMP_DIR}/${OUTBASE} -mw $MIN_WEIGHT -tt $TRIM_THRES \
+	$EXCLUDE_BED_FMT \
+	$LUMPY_DISC_STRING \
+	$LUMPY_SPL_STRING \
 	> $OUTPUT.bedpe
+    echo "done"
 
     # clean up
     rm -r ${TEMP_DIR}
